### PR TITLE
made deployable to niemasd's github pages

### PR DESCRIPTION
**Pull request by CatFish47**
Made deployable to https://niemasd.github.io/FAVITES-Lite by following the instructions from [here](https://github.com/gitname/react-gh-pages).

To deploy, navigate the the `/webapp` directory and run `npm install` to install all dependencies and then `npm run deploy` to deploy

### CODE REVIEW

**Comment by niemasd** [comment]
Thanks! Can you incorporate those commands into a GitHub Action that automatically gets executed upon push and handles compiling + publishing the website on GitHub Pages? I think Daniel might have experience with this. This might also give some guidance:

https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by CatFish47** [comment]
Auto deploy should be set up now! Let me know if you see any issues

**Comment by niemasd** [comment]
@CatFish47 Thanks, just merged! Some quick requests for updates:

1. Can you add a "Load" function, where a user can upload an existing config JSON that they want to start off with?
2. Can you add a scrollbar for the left menu so it's clear that the user can scroll down to see the rest of the items?
3. Can you make the currently-selected section in the left menu a bit more visually obvious? Right now, it's a somewhat thin blue vertical line, but it would be good to make it a bit more visually obvious what is selected
4. When I first go to the website, because nothing is selected, the main panel is blank. Can you add some informational text e.g. "To get started, either load an existing config file via the Load button above, or click on a module in the left menu"?

**Comment by niemasd** [comment]
Oh also, I think some of the descriptions are messed up; might be an issue with the string parsing functions? For example, the following shows up for Contact Network:

> The Contact Network graph model describes all social interactions: - Nodes represent individuals in the population - Edges represent all interactions across which the pathogen can transmit - Currently, FAVITES-Lite only supports static (i.e., unchanging) contact networks

whereas it should be:

> The Contact Network graph model describes all social interactions:
> \- Nodes represent individuals in the population
> \- Edges represent all interactions across which the pathogen can transmit
> \- Currently, FAVITES-Lite only supports static (i.e., unchanging) contact networks

Similar thing happen when I pick e.g. Newman-Watts-Strogatz (NWS) for Contact Network. The description says the following:

> The Newman-Watts-Strogatz (NWS) model is an undirected graph model as follows: 1. Start with a ring of n nodes 2. Connect each node with its k nearest neighbors 3. For each edge (u,v) in the ring, add a new random edge (u,w) with probability p

but it should be the following:

> The Newman-Watts-Strogatz (NWS) model is an undirected graph model as follows:
> 1. Start with a ring of n nodes
> 2. Connect each node with its k nearest neighbors
> 3. For each edge (u,v) in the ring, add a new random edge (u,w) with probability p

**Pull request merged**
